# Site Settings
title: 'My Resume'
url: 'http://webjeda.com'
baseurl: '/online-cv' #change it according to your repository name

# Enable one of these styles by removing #. Style will be applied only after restarting the build or serve.
#style: styles-2
#style: styles-3
#style: styles-4
#style: styles-5
#style: styles-6

#Profile information
name: Ashwin Rajendran
tagline: Business Analyst
pic: profile.png  #place a 100x100 picture inside /assets/images/ folder and provide the name of the file below
summary: 'Business Data Analyst with 4+ years of experience in analyzing, visualizing data and providing business related solutions. Aiming to utilize my strong skills and analytical abilities to fulfill the organization’s goals. Possess a Masters in Technology Management and Innovation from New York University. '

#sidebar links
email: ashwinraj@nyu.edu
phone: +1(201)889-9959
website: blog.webjeda.com #do not add http://
linkedin: ashwinrajendran
github: AshwinRajendran
twitter: '@webjeda'
#Update all the sections by editing the files inside _data folder.

# Tracker
analytics: UA-83979019-1

# Build settings
encoding: "utf-8"
compress_html: # - http://jch.penibelst.de/
  clippings: all
  ignore:
    envs: development
